seed: 42

# Dataset
dataset : 'sample_data'
# dataset_root is the project root. The dataloader will look for 'sample_data' inside it.
dataset_root : './'

# Model
# This model uses standard regression, so both options are set to False.
use_ordinal_regression : False
use_encoder : False

train_batch_size: 64
test_batch_size: 128
train_workers: 4
test_workers: 0

img_size: 224
# The following values are ignored since use_ordinal_regression is False.
ordinal_bins : 60
Hb_minima : 3
Hb_maxima : 18
disc_shift : 0

epochs: 300
start_ib_epoch: 150

backbone : 'resnext50_32x4d'
optimizer : 'sgd'
scheduler: ''
lr: 0.0005 # Learning rate suitable for regression mode

weight_decay : 0.00005
