Hb_maxima: 18
Hb_minima: 3
alpha: 0.01
backbone: resnext50_32x4d
bins: 60
dataset: sample_data
dataset_root: ./
device: 0
disc_shift: 0
epochs: 300
exp_name: image-bins60
fold: 0
gamma: 1.5
img_size: 224
lambda_1: 1.0e-06
lambda_2: 0.0001
lambda_3: 1.5
log_dir: log_bins/train/image-bins60-fold0
lr: 0.01
no_enc: false
no_ord: false
optimizer: sgd
ordinal_bins: 60
scheduler: ''
seed: 42
start_ib_epoch: 150
test_batch_size: 128
test_workers: 0
train_batch_size: 64
train_workers: 4
use_encoder: true
use_ordinal_regression: true
weight_decay: 5.0e-05
